### ISSUE TITLE
Geodiff cannot create diffs when there are too many fields

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/geodiff#106]
I think the limit is 250 fields. After that Geodiff fails to sync.

**Comment by alexbruy** [comment]
Do we have a test project for this issue?

**Comment by saberraz** [comment]
@alexbruy I have created this: https://app.merginmaps.com/projects/saber/large_field_no which appears to work with a couple of changes. I think the issue was randomly surfacing so it is difficult to reproduce.

@jozef-budac it would be good to create a test case for this (ideally should be an automatic one).

**Comment by tomasMizera** [comment]
We could not reproduce this issue for quite some time now
