### ISSUE TITLE
Better handle sqlite error logs

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/geodiff#135]
Currently, geodiff registers its logger in GEODIFF_init() as the global log callback:
```cpp
sqlite3_config( SQLITE_CONFIG_LOG, _errorLogCallback );
```

This may cause issues:
- when used in another app, this may be in conflict with the app's log config for sqlite
- geodiff may capture also logs that were not triggered by geodiff, making the log output confusing
- if there are multiple instances of geodiff created within a single process, errors may not end up in the correct logger

It should be possible to catch errors on per-connection level without registering global error callback: http://www.sqlite.org/c3ref/errcode.html

**Comment by PeterPetrik** [comment]
best after #136 is implemented
