### ISSUE TITLE
GeoDiffLibError while trying to use Python geodiff.make_copy from SQLite to PostgreSQL

### ISSUE THREAD

**Issue by mdouchin** [MerginMaps/geodiff#163]
Hi all GeoDiff team !

I have tried with the pip3 version

```python
import pygeodiff
geodiff = pygeodiff.GeoDiff()
```
and with the Mergin plugin way `import Mergin.mergin.deps.pygeodiff as pygeodiff`

I have an error while trying to copy a GeoPackage to a local PostgreSQL database. No error when doing the same with the sqlite driver for output format.

```
>>> import pygeodiff
>>> geodiff = pygeodiff.GeoDiff()
>>> geodiff.make_copy('sqlite', '', 'layers.gpkg', 'postgres', 'host=localhost port=5432 user=mdouchin password=***** dbname=geodiff', 'schema')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mdouchin/.local/lib/python3.8/site-packages/pygeodiff/main.py", line 209, in make_copy
    return self.clib.make_copy(driver_src, driver_src_info, src, driver_dst, driver_dst_info, dst)
  File "/home/mdouchin/.local/lib/python3.8/site-packages/pygeodiff/geodifflib.py", line 322, in make_copy
    _parse_return_code(res, "make_copy")
  File "/home/mdouchin/.local/lib/python3.8/site-packages/pygeodiff/geodifflib.py", line 41, in _parse_return_code
    raise GeoDiffLibError(msg)
pygeodiff.geodifflib.GeoDiffLibError: make_copy
```
Perhaps the PostgreSQL driver is not enabled ?

Thanks in advance for your help

**Comment by PeterPetrik** [comment]
Yes, pip version does not have postgresql driver (https://github.com/lutraconsulting/geodiff/blob/ae0474859818736460faef406fb23e9be15e811e/setup.py#L11 and https://github.com/lutraconsulting/geodiff/blob/ae0474859818736460faef406fb23e9be15e811e/geodiff/CMakeLists.txt#L18). 
In db-sync we compile it ourselves and replace binary https://github.com/lutraconsulting/mergin-db-sync/blob/6626ef0c86c8adf681f64268fa0ebe6e1dc4530d/Dockerfile#L23

Indeed the error should be fixed to be more descriptive (not native exception), but we do not plan to ship PostgreSQL driver by default by now (it is quite challenge to have it working on all platforms even with sqlite)

**Comment by mdouchin** [comment]
Thanks a lot for your answer

**Comment by mdouchin** [comment]
By the way, I just use the provided [Dockerfile](https://github.com/MerginMaps/mergin-db-sync/blob/master/Dockerfile) to build an image and then run geodiff. It seems to work well.
