### ISSUE TITLE
support Apple M1/M2 architecture in pygeodiff

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/geodiff#199]
This one is blocked by https://github.com/actions/runner-images/issues/2187

related to https://github.com/MerginMaps/mergin-py-client/issues/164

**Comment by wonder-sk** [comment]
:tada: Since last week, github actions have beta support for Apple Silicon: https://github.com/actions/runner-images/issues/8439

**Comment by PeterPetrik** [comment]
If I understand it correctly it is available only on non-public `large` runnings, intended for open-source in early '24

**Comment by PeterPetrik** [comment]
`macOS-14` now supports arm64 architecture
